stages:
  - build
  - test
  - deploy

before_script:
  - cd $CI_PROJECT_DIR/TourGuide

maven_build:
  stage: build
  image: maven:3.8-openjdk-17
  script:
    - mvn -f pom.xml clean install

maven_test:
  stage: test
  image: maven:3.8-openjdk-17
  script:
    - mvn test

maven_deploy:
  stage: deploy
  image: maven:3.8-openjdk-17
  script:
    - echo "My deployment commands"
    - mvn clean compile install
    - cp target/*.jar /deploymentdirectory
