stages :
  -build

variables:
  MAVEN_CLI_OPS: "-s .m2/settings.xml --batch-mode"

maven_build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - target/*.jar